export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const TOGGLE_ON_DROPDOWN = "TOGGLE_ON_DROPDOWN";
export const TOGGLE_OFF_DROPDOWN = "TOGGLE_OFF_DROPDOWN";
