// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOADING = "LOADING";

// profile
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

// find user
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_FAIL = "FIND_USER_FAIL";

// get following users
export const GET_FOLLOWING_USER_SUCCESS = "GET_FOLLOWING_USER_SUCCESS";
export const GET_FOLLOWING_USER_FAIL = "GET_FOLLOWING_USER_FAIL";

// utils
export const TOGGLE_ON_DROPDOWN = "TOGGLE_ON_DROPDOWN";
export const TOGGLE_OFF_DROPDOWN = "TOGGLE_OFF_DROPDOWN";
export const TOGGLE_ON_FOLLOW_LIST = "TOGGLE_ON_FOLLOW_LIST";
export const TOGGLE_OFF_FOLLOW_LIST = "TOGGLE_OFF_FOLLOW_LIST";
export const TOGGLE_ON_CREATE_POST = "TOGGLE_ON_CREATE_POST";
export const TOGGLE_OFF_CREATE_POST = "TOGGLE_OFF_CREATE_POST";
export const TOGGLE_ON_BACKDROP = "TOGGLE_ON_BACKDROP";
export const TOGGLE_OFF_BACKDROP = "TOGGLE_OFF_BACKDROP";

// get posts
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
